"use client";
/* eslint-disable jsx-a11y/alt-text */
import { useState } from "react";
import Head from "next/head";
import axios from "axios";
import Image from "next/image";
import { BsSearch } from "react-icons/bs";
import Weather from "./components/Weather";
import Spinner from "./components/Spinner";
export default function Home() {
  const [city, setCity] = useState("");
  const [weather, setWeather] = useState({});
  const [loading, setLoading] = useState(false);

  const url = `https://api.openweathermap.org/data/2.5/weather?q=${city}&units=imperial&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}`;

  const fetchWeather = (e) => {
    e.preventDefault();
    setLoading(true);
    axios.get(url).then((response) => {
      setWeather(response.data);
    });
    setCity("");
    setLoading(false);
  };

  if (loading) {
    return <Spinner />;
  } else {
    return (
      <div>
        <Head>
          <title>Weather - Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="../public/next.svg" />
        </Head>

        {/*Overlay */}
        <div className="absolute top-0 left-0 right-0 bottom-0 bg-black/60 z-[1]" />
        <Image src="/photo.png" layout="fill" className="object-cover" />

        {/**Search */}
        <div className="relative flex  flex-col justify-between items-center max-w-[500px] w-full m-auto pt-4 text-white z-10">
          <form
            onSubmit={fetchWeather}
            className="flex justify-between items-center w-full m-auto p-3 bg-transparent border border-gray-300  text-white rounded-2xl"
          >
            <input
              onChange={(e) => setCity(e.target.value)}
              className="bg-transparent border-none text-white focus:outline-none text-2xl"
              type="text"
              placeholder="Search City"
            />
            <button onClick={fetchWeather}>
              <BsSearch size={30} />
            </button>
          </form>
        </div>

        {/**Weather */}

        {weather.main && <Weather data={weather} />}
      </div>
    );
  }
}
